# Generated by Django 4.1.1 on 2023-04-17 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedUser",
            fields=[
                ("phone", models.CharField(max_length=20)),
                ("patronymic", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="origin_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                ("direction", models.CharField(max_length=100, null=True)),
                ("line_place", models.FloatField(default=0.5, null=True)),
                ("line_width", models.IntegerField(default=20, null=True)),
                (
                    "model",
                    models.CharField(
                        default="default model", max_length=100, null=True
                    ),
                ),
                ("pid", models.IntegerField(default=None, null=True)),
                ("status", models.IntegerField(default=0)),
                ("current_counter", models.IntegerField(default=0)),
                (
                    "sample_image",
                    models.FileField(null=True, upload_to="sample_images/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.extendeduser",
                    ),
                ),
            ],
        ),
    ]
