# Generated by Django 4.1.1 on 2023-04-09 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                ("direction", models.CharField(max_length=100)),
                ("line_place", models.FloatField(default=0.5)),
                ("line_width", models.IntegerField(default=20)),
                ("model", models.CharField(max_length=100)),
                ("pid", models.IntegerField(default=None, null=True)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedUser",
            fields=[
                ("phone", models.CharField(max_length=20)),
                ("patronymic", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="origin_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
