# Generated by Django 4.2 on 2023-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='current_counter',
            field=models.IntegerField(default=0),
        ),
    ]
