# Generated by Django 4.0.4 on 2023-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('line_place', models.FloatField(default=0.5)),
                ('line_width', models.IntegerField(default=20)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
